# Generated by Django 4.2.5 on 2023-11-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_externo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_interno', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=60, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('t_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('t_oficina', models.CharField(blank=True, max_length=50, null=True)),
                ('t_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('cuenta_contable', models.CharField(blank=True, max_length=20, null=True)),
                ('plazo', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('clave', models.CharField(default=0, max_length=3)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Regimen',
            },
        ),
    ]
