# Generated by Django 4.2.5 on 2023-10-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cli.regimen'),
        ),
    ]
