# Generated by Django 4.2.5 on 2023-10-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0004_zona'),
        ('cli', '0003_alter_cliente_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dom.zona'),
        ),
    ]
