# Generated by Django 4.2.5 on 2023-10-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0004_alter_cliente_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimen',
            name='clave',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
