# Generated by Django 4.2.5 on 2023-11-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('consignacion', models.BooleanField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('comentario_oc', models.CharField(blank=True, max_length=100, null=True)),
                ('divisa', models.CharField(blank=True, choices=[('', 'Seleccione'), ('P', 'Pesos (MXN)'), ('D', 'Dólares (USD)')], max_length=1, null=True)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comentario_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarimas', models.PositiveIntegerField(default=0)),
                ('cajas_tarimas', models.PositiveIntegerField(default=0)),
                ('total_cajas', models.PositiveIntegerField(default=0)),
                ('flete1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('flete2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aduana_mx', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sobrepeso_mx', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aduana_us', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sobrepeso_us', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logistica', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venta_consignacion', models.CharField(blank=True, choices=[('', 'Seleccione'), ('S', 'SI'), ('N', 'NO')], max_length=1)),
                ('oc_local', models.CharField(blank=True, choices=[('', 'Seleccione'), ('S', 'SI'), ('N', 'NO')], max_length=1)),
                ('total_precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Ordenes Compra',
            },
        ),
        migrations.CreateModel(
            name='Orden_Compra_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_reportar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Ordenes Compra Detalle',
            },
        ),
        migrations.CreateModel(
            name='Orden_Compra_Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Ordenes Compra Estatus',
            },
        ),
    ]
