# Generated by Django 4.2.5 on 2023-10-15 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod', '0005_alter_etiqueta_nombre_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dom', '0005_domicilio_calle_domicilio_colonia_domicilio_cp_and_more'),
        ('prov', '0003_alter_proveedor_options'),
        ('cli', '0005_alter_regimen_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('consignacion', models.BooleanField()),
                ('libre_abordo', models.CharField(blank=True, choices=[('', 'Seleccione'), ('E', 'Empaque'), ('P', 'Puesto en Bodega')], max_length=1)),
                ('fecha_entrega', models.DateTimeField()),
                ('comentario_oc', models.CharField(blank=True, max_length=100, null=True)),
                ('divisa', models.CharField(blank=True, choices=[('', 'Seleccione'), ('P', 'Pesos (MXN)'), ('D', 'Dólares (USD)')], max_length=1)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comentario_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarimas', models.PositiveIntegerField(default=0)),
                ('cajas_tarimas', models.PositiveIntegerField(default=0)),
                ('total_cajas', models.PositiveIntegerField(default=0)),
                ('flete1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('flete2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aduana_mx', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sobrepeso_mx', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aduana_us', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sobrepeso_us', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logistica', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venta_consignacion', models.CharField(blank=True, choices=[('', 'Seleccione'), ('S', 'SI'), ('N', 'NO')], max_length=1)),
                ('oc_local', models.CharField(blank=True, choices=[('', 'Seleccione'), ('S', 'SI'), ('N', 'NO')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cli.cliente')),
                ('embarcador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarcador', to=settings.AUTH_USER_MODEL)),
                ('entregar_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dom.domicilio')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prov.proveedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordenes Compra',
            },
        ),
        migrations.CreateModel(
            name='Orden_Compra_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_reportar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.etiqueta')),
                ('medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.medida')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oc.orden_compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.producto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordenes Compra Detalle',
            },
        ),
    ]
