# Generated by Django 4.2.5 on 2023-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra',
            name='divisa',
            field=models.CharField(blank=True, choices=[('', 'Seleccione'), ('P', 'Pesos (MXN)'), ('D', 'Dólares (USD)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='libre_abordo',
            field=models.CharField(blank=True, choices=[('', 'Seleccione'), ('E', 'Empaque'), ('P', 'Puesto en Bodega')], max_length=1, null=True),
        ),
    ]
