# Generated by Django 4.2.5 on 2023-11-01 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cli', '0002_initial'),
        ('prod', '0001_initial'),
        ('oc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prov', '0001_initial'),
        ('dom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra_estatus',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.etiqueta'),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle',
            name='medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prod.medida'),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oc.orden_compra'),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prod.producto'),
        ),
        migrations.AddField(
            model_name='orden_compra_detalle',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cli.cliente'),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='embarcador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarcador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='entregar_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dom.domicilio'),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oc.orden_compra_estatus'),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prov.proveedor'),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
