# Generated by Django 4.2.5 on 2023-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0003_remove_orden_compra_libre_abordo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden_compra',
            old_name='cantidad',
            new_name='total_cantidad',
        ),
        migrations.RenameField(
            model_name='orden_compra',
            old_name='total',
            new_name='total_importe',
        ),
        migrations.RenameField(
            model_name='orden_compra_detalle',
            old_name='costo_unitario',
            new_name='gasto',
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='total_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orden_compra',
            name='total_precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
