# Generated by Django 4.2.5 on 2023-11-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dom', '0001_initial'),
        ('cli', '0001_initial'),
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Forma_Pago',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('contacto_embarque', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('t_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('t_oficina', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_externo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_interno', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=60, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('zona', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_venta', models.EmailField(blank=True, max_length=254, null=True)),
                ('t_celular_venta', models.CharField(blank=True, max_length=50, null=True)),
                ('t_oficina_venta', models.CharField(blank=True, max_length=50, null=True)),
                ('plazo', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite_credito', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cuenta_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('clabe', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prov.banco')),
                ('categorias', models.ManyToManyField(to='prod.categoria')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dom.entidad')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prov.forma_pago')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dom.municipio')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dom.pais')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cli.regimen')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
