# Generated by Django 4.2.5 on 2023-10-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prov', '0002_forma_pago_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
