# Generated by Django 4.2.5 on 2023-10-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_venta', to='prod.unidad_compra'),
        ),
        migrations.DeleteModel(
            name='Unidad_Venta',
        ),
    ]
